//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace newServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCTOR
    {
        public DOCTOR()
        {
            this.MEDICAL_EXAM = new HashSet<MEDICAL_EXAM>();
            this.MEDICAL_RECORD = new HashSet<MEDICAL_RECORD>();
            this.SCHEDULE = new HashSet<SCHEDULE>();
        }
    
        public decimal ID { get; set; }
        public string PASSWORD { get; set; }
        public string DEPT_NAME { get; set; }
        public string NAME { get; set; }
        public string POSITION { get; set; }
        public Nullable<System.DateTime> LASTLOGIN_TIME { get; set; }
        public System.DateTime CREATION_TIME { get; set; }
        public string E_MAIL { get; set; }
        public string GENDER { get; set; }
        public decimal AGE { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual ICollection<MEDICAL_EXAM> MEDICAL_EXAM { get; set; }
        public virtual ICollection<MEDICAL_RECORD> MEDICAL_RECORD { get; set; }
        public virtual ICollection<SCHEDULE> SCHEDULE { get; set; }
    }
}
