//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace newServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRUG_INVENTORY
    {
        public DRUG_INVENTORY()
        {
            this.INFUSION = new HashSet<INFUSION>();
            this.PRESCRIBE = new HashSet<PRESCRIBE>();
        }
    
        public decimal ID { get; set; }
        public decimal DRUG_ID { get; set; }
        public decimal PRICE { get; set; }
        public decimal SURPLUS { get; set; }
        public Nullable<decimal> SOLD_NUMBER { get; set; }
    
        public virtual DRUG DRUG { get; set; }
        public virtual ICollection<INFUSION> INFUSION { get; set; }
        public virtual ICollection<PRESCRIBE> PRESCRIBE { get; set; }
    }
}
