//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace newServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRUG
    {
        public DRUG()
        {
            this.DRUG_INVENTORY = new HashSet<DRUG_INVENTORY>();
        }
    
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public string CODE { get; set; }
        public string STANDARD { get; set; }
        public string MANUFACTOR { get; set; }
        public decimal PAURCH_PRICE { get; set; }
        public decimal PRIME { get; set; }
    
        public virtual ICollection<DRUG_INVENTORY> DRUG_INVENTORY { get; set; }
    }
}
