//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace newServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAM_ITEM
    {
        public EXAM_ITEM()
        {
            this.MEDICAL_EXAM = new HashSet<MEDICAL_EXAM>();
        }
    
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public decimal EXPENSE { get; set; }
        public decimal BUILDING_ID { get; set; }
        public decimal ROOM_ID { get; set; }
        public string REFERENCE_VALUE { get; set; }
    
        public virtual ICollection<MEDICAL_EXAM> MEDICAL_EXAM { get; set; }
    }
}
