//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace newServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOREGROUND_INFORMATION
    {
        public decimal ID { get; set; }
        public string E_MAIL { get; set; }
        public string INFORMATION { get; set; }
        public decimal PATIENT_ID { get; set; }
        public string STATE { get; set; }
    
        public virtual PATIENT PATIENT { get; set; }
    }
}
