//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace newServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFUSION
    {
        public decimal RECORD_ID { get; set; }
        public decimal ITEM_ID { get; set; }
        public decimal DRUG_ID { get; set; }
        public decimal EXPENSE { get; set; }
        public string STATE { get; set; }
        public decimal NUMBERS { get; set; }
    
        public virtual DRUG_INVENTORY DRUG_INVENTORY { get; set; }
        public virtual MEDICAL_RECORD MEDICAL_RECORD { get; set; }
        public virtual OPERATION OPERATION { get; set; }
    }
}
