//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace newServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTORY
    {
        public INVENTORY()
        {
            this.INVENTORY_EXAMPLE = new HashSet<INVENTORY_EXAMPLE>();
        }
    
        public decimal LIST_NUMBRE { get; set; }
        public string INVENTORY_PEOPLE { get; set; }
        public System.DateTime INVENTORY_DATE { get; set; }
        public string REMARK { get; set; }
    
        public virtual ICollection<INVENTORY_EXAMPLE> INVENTORY_EXAMPLE { get; set; }
    }
}
