//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace newServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICAL_TREATEMENT
    {
        public decimal RECORD_ID { get; set; }
        public decimal SEQUENCE { get; set; }
        public string TITLE { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual MEDICAL_RECORD MEDICAL_RECORD { get; set; }
    }
}
