//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace newServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPERATION
    {
        public OPERATION()
        {
            this.CLINICAL = new HashSet<CLINICAL>();
            this.INFUSION = new HashSet<INFUSION>();
        }
    
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public decimal PRICE { get; set; }
        public string CODE { get; set; }
    
        public virtual ICollection<CLINICAL> CLINICAL { get; set; }
        public virtual ICollection<INFUSION> INFUSION { get; set; }
    }
}
