//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace newServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PATIENT
    {
        public PATIENT()
        {
            this.FOREGROUND_INFORMATION = new HashSet<FOREGROUND_INFORMATION>();
            this.MEDICAL_RECORD = new HashSet<MEDICAL_RECORD>();
            this.OPPOINTMENT = new HashSet<OPPOINTMENT>();
            this.REGISTRATION_RECORD = new HashSet<REGISTRATION_RECORD>();
        }
    
        public decimal ID { get; set; }
        public string PASSWORD { get; set; }
        public string NAME { get; set; }
        public string EXPLANATION { get; set; }
        public Nullable<System.DateTime> LASTLOGIN_TIME { get; set; }
        public System.DateTime CREATION_TIME { get; set; }
        public string E_MAIL { get; set; }
        public string GENDER { get; set; }
        public decimal AGE { get; set; }
        public System.DateTime BIRTHDAY { get; set; }
        public string IDENTITY { get; set; }
        public Nullable<decimal> COUNT { get; set; }
    
        public virtual ICollection<FOREGROUND_INFORMATION> FOREGROUND_INFORMATION { get; set; }
        public virtual ICollection<MEDICAL_RECORD> MEDICAL_RECORD { get; set; }
        public virtual ICollection<OPPOINTMENT> OPPOINTMENT { get; set; }
        public virtual ICollection<REGISTRATION_RECORD> REGISTRATION_RECORD { get; set; }
    }
}
