//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace newServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULE
    {
        public SCHEDULE()
        {
            this.OPPOINTMENT = new HashSet<OPPOINTMENT>();
            this.REGISTRATION_RECORD = new HashSet<REGISTRATION_RECORD>();
        }
    
        public decimal ID { get; set; }
        public System.DateTime BEGIN_TIME { get; set; }
        public System.DateTime END_TIME { get; set; }
        public decimal BUILDING_ID { get; set; }
        public decimal ROOM_ID { get; set; }
        public decimal DOCTOR_ID { get; set; }
    
        public virtual DOCTOR DOCTOR { get; set; }
        public virtual ICollection<OPPOINTMENT> OPPOINTMENT { get; set; }
        public virtual ICollection<REGISTRATION_RECORD> REGISTRATION_RECORD { get; set; }
    }
}
